#!/bin/bash

echo "🚀 Manual API Deployment Guide"
echo "=============================="
echo ""
echo "Since Render Blueprint is not picking up the FastAPI configuration,"
echo "let's deploy manually using Web Service instead of Blueprint."
echo ""
echo "📋 Step-by-Step Instructions:"
echo ""
echo "1️⃣ Go to Render Dashboard:"
echo "   https://render.com"
echo ""
echo "2️⃣ Create New Web Service:"
echo "   - Click 'New' → 'Web Service' (NOT Blueprint)"
echo "   - Connect your GitHub repository: UllasCL/reddit-gpt-summarizer"
echo ""
echo "3️⃣ Configure the Service:"
echo "   - Name: reddit-gpt-api"
echo "   - Environment: Python 3"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: uvicorn simple_api:app --host 0.0.0.0 --port \$PORT"
echo ""
echo "4️⃣ Set Environment Variables:"
echo "   OPENAI_ORG_ID=org-CfNfpBsetCb4Q8dcxGNm0ORf"
echo "   OPENAI_API_KEY=your_openai_api_key_here"
echo "   REDDIT_CLIENT_ID=0maibsKtYFtrIvD5jFwyfg"
echo "   REDDIT_CLIENT_SECRET=z5T4kR2iD5PiBmyIPmGgynug_HT41A"
echo "   REDDIT_USERNAME=Otherwise_Still_734"
echo "   REDDIT_PASSWORD=kH9kPAqJVnbKHm"
echo "   REDDIT_USER_AGENT=linux:com.Otherwise_Still_734.reddit-gpt-summarizer:v1.0.0 (by /u/Otherwise_Still_734)"
echo "   ANTHROPIC_API_KEY=your_anthropic_api_key_here (optional)"
echo ""
echo "5️⃣ Deploy:"
echo "   - Click 'Create Web Service'"
echo "   - Wait for deployment to complete"
echo ""
echo "🎯 Your API will be available at:"
echo "   https://reddit-gpt-api.onrender.com"
echo ""
echo "🧪 Test the deployment:"
echo "   curl https://reddit-gpt-api.onrender.com/"
echo ""
echo "📱 For Chrome Extension:"
echo "   const apiUrl = 'https://reddit-gpt-api.onrender.com/summarize';"
echo ""
echo "✅ This approach bypasses the Blueprint configuration issues!" 